#!/bin/bash
#SBATCH -J yearbook5_20_epochs_128_l1           # job namu
#SBATCH -o yearbook5_20_epochs_128_l1.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 1 -N 1               # total number of mpi tasks requested
#SBATCH -p gpu     # queue (partition) -- normal, development, etc.
#SBATCH -t 12:00:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=pandian@cs.utexas.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes

./run.sh --DATASET_TYPE=yearbook --type=valid --model_architecture=alexnet --load_saved_model=0 --checkpoint_file_name=checkpoint5.h5 --use_pretraining=1 --fine_tuning_method=end-to-end --batch_size=128 --num_epochs=20 --loss=l1 --optimizer=sgd